### ISSUE TITLE
Raspberry Pi Zero W with Lora HAT Dragino (SX1276)

### ISSUE THREAD

**Issue by pat-fly** [astir13/SoftRF_standalone#5]
Hello
I set up the Raspberry Pi Zero W with the Dragino Lora HAT exactly the same as on the Wiki. I followed the steps downloading SoftRF and libraries and compiled.
When I start the program it says:

> $ cat /dev/ttyAMA0 | sudo ./SoftRF
> WARNING! Neither SX1276, CC13XX or NRF905 RFIC is detected!

I know there is a problem with serial ports on RPI3 due to bluetooth. But I switched it off and also I can get the GPS NMEA on /dev/ttySerial0. But I think this is not the problem of this error. So I went through checking the pin definitions and it looks okay. Everything like on the wiring picture of the wiki.
What am I doing wrong? What can I do to debug?

**Comment by astir13** [comment]
Ok, better late than never: you posted your question to the SoftRF_standalone project, which is not supporting RPi, but only the standalone version (therefore the name ;-); sorry, I would suggest you go to the SoftRF project and follow the question/discussion rules there, maybe try to ask your question in the forum/discussion.
